
BEGIN { FS = ":" } ; 
{ 
    print "#!/bin/bash -x"                                                              >> "action.sh"
    print "#bibi Email " $2  " CamId " $4 " Password " $6 " Number of pictures " $8 " MovieDuration "  $10 " VideoRecording " $12                                                                                           >> "action.sh"
    print "UPDATE_DELAY=60"                                                             >> "action.sh"
    print "if [ '"$12"' != 'Start' ]; then"                                             >> "action.sh"
    print "    sleep $UPDATE_DELAY"                                                     >> "action.sh"
    print "    exit 1;"                                                                 >> "action.sh"
    print "fi"                                                                          >> "action.sh"
    print "if [ "$4" != $CAM_ID ]; then"                                                >> "action.sh"
    print "    sleep $UPDATE_DELAY"                                                     >> "action.sh"
    print "    exit 1;"                                                                 >> "action.sh"
    print "fi"                                                                          >> "action.sh"
    print "if ['"$6"' != $CAM_PSWD ]; then"                                             >> "action.sh"
    print "    sleep $UPDATE_DELAY"                                                     >> "action.sh"
    print "    exit 1;"                                                                 >> "action.sh"
    print "fi"                                                                          >> "action.sh"
    print "if diff info.log info_old.log >/dev/null ; then"                             >> "action.sh"
    print "    echo \"Same info files.\""                                               >> "action.sh" 
    print "else"                                                                        >> "action.sh"
    print "    mpack -s ecam_params info.log " $2                                       >> "action.sh"
    print "fi"                                                                          >> "action.sh"

    print "PIC_DIR=\"/home/ubuntu/.motion/test\" "                                      >> "action.sh"
    print "PIC_COUNTER=1"                                                               >> "action.sh"
    print "STANDBY_COUNTER=1"                                                           >> "action.sh"
    print "motion -c /home/ubuntu/.motion/motion.conf"                                  >> "action.sh"
    print "while true; do"                                                              >> "action.sh"
    print "       if [ \"$(ls -A $PIC_DIR)\" ]; then"                                   >> "action.sh"
    print "           echo \"WARNING! Motion detected!\""                               >> "action.sh"
    print "           last_file=$(ls -t $PIC_DIR| tail -1)"                             >> "action.sh"
    print "           if [[ \"$PIC_DIR/$last_file\" == *.swf ]]; then"                  >> "action.sh"
    print "               rm -f $PIC_DIR/$last_file"                                    >> "action.sh"
    print "               continue"                                                     >> "action.sh"
    print "           fi"                                                               >> "action.sh"
    #print "           mpack -s picture $PIC_DIR/$last_file " $2                         >> "action.sh"
    print "           sshpass -p 'roni' scp $PIC_DIR/$last_file roni@192.241.230.171:/home/roni/test_videos" >> "action.sh"
    print "           echo \"$PIC_DIR/$last_file\""                                     >> "action.sh"
    print "           rm -f $PIC_DIR/$last_file"                                        >> "action.sh"
    print "           PIC_COUNTER=$(($PIC_COUNTER+1)) "                                 >> "action.sh"
    print "           if  [ $PIC_COUNTER -gt "$8" ]; then"                              >> "action.sh"
    print "               break"                                                        >> "action.sh"
    print "           fi"                                                               >> "action.sh"
    print "       else"                                                                 >> "action.sh"
    print "           echo \"No motion detected.\""                                     >> "action.sh"
    print "           STANDBY_COUNTER=$(($STANDBY_COUNTER+1)) "                         >> "action.sh"
    print "           if  [ $STANDBY_COUNTER -gt 60 ]; then"                            >> "action.sh"
    print "               break"                                                        >> "action.sh"
    print "           fi"                                                               >> "action.sh"
    print "           sleep 1"                                                          >> "action.sh"
    print "       fi"                                                                   >> "action.sh"
    print "done"                                                                        >> "action.sh"

    print "pid=$(head /home/ubuntu/.motion/motion.pid)"                                 >> "action.sh"
    print "echo \"Stop motion program!\""                                               >> "action.sh"
    print "kill -9 $pid"                                                                >> "action.sh"
    print "sleep 1"                                                                     >> "action.sh"
    print "rm -f $PIC_DIR/*"                                                            >> "action.sh"  

    print "if  [ $STANDBY_COUNTER -lt 60 ]; then"                                       >> "action.sh"
    print "    /home/ubuntu/bin/ffmpeg -f video4linux2 -i /dev/video0 -c:v libx264 -t "$10" -pix_fmt yuv420p -preset veryfast -tune fastdecode -profile:v baseline  -r 10 -me_range 4 -x264opts no-deblock movie_1.mp4 " >> "action.sh" 
    #print "    mpack -s video movie_1.mp4 "$2                                               >> "action.sh"
    print "    movie_file=$(date +\"%m_%d_%Y_%H_%M_%S\").mp4"                           >> "action.sh"
    print "    sshpass -p 'roni' scp movie_1.mp4 roni@192.241.230.171:/home/roni/test_videos/$movie_file" >> "action.sh"
    print "fi"                                                                          >> "action.sh"
}
